module NATS
  class KeyValue
    KV_OP: 'KV-Operation'
    KV_DEL: 'DEL'
    KV_PURGE: 'PURGE'
    MSG_ROLLUP_SUBJECT: 'sub'
    MSG_ROLLUP_ALL: 'all'
    ROLLUP: 'Nats-Rollup'

    @name: String
    @stream: String
    @pre: String
    @js: JetStream
    @direct: bool

    def initialize: (Hash[Symbol, untyped]) -> void

    def get: (String, ?Hash[Symbol, untyped]) -> Entry

    private def _get: (String, ?Hash[Symbol, untyped]) -> Entry

    def put: (String, untyped) -> Integer

    def create: (String, untyped) -> Integer

    EXPECTED_LAST_SUBJECT_SEQUENCE: 'Nats-Expected-Last-Subject-Sequence'

    def update: (String, untyped, ?Hash[Symbol, untyped]) -> Integer

    def delete: (String, ?Hash[Symbol, untyped]) -> Integer

    def purge: (String) -> JetStream::PubAck

    def status: () -> BucketStatus

    class Entry < Struct[untyped]

    def watchall: (?Hash[Symbol, untyped]) -> KeyWatcher

    def keys: (?Hash[Symbol, untyped], ?Enumerable[String]) -> Enumerator[String]

    def history: (String, ?Hash[Symbol, untyped]) -> Enumerator[String]

    STATUS_HDR: 'Status'
    DESC_HDR: 'Description'
    CTRL_STATUS: '100'
    LAST_CONSUMER_SEQ_HDR: 'Nats-Last-Consumer'
    LAST_STREAM_SEQ_HDR: 'Nats-Last-Stream'
    CONSUMER_STALLED_HDR: 'Nats-Consumer-Stalled'

    def watch: (String, ?Hash[Symbol, untyped]) -> KeyWatcher

    class KeyWatcher
      include MonitorMixin
      include Enumerable[untyped]

      def initialize: (NATS::JetStream) -> void
    end
  end
end
