language: ruby

rvm:
  - 3.1.6
  - 3.2.5
  - 3.3.5

cache:
  directories:
  - $HOME/nats-server

before_install:
  - bash ./scripts/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

sudo: required
dist: jammy

addons:
  hosts:
    - server-A.clients.nats-service.localhost
    - server-A.clients.fake-nats-service.localhost
    - server-A.routes.nats-service.localhost
    - server-A.routes.fake-nats-service.localhost

jobs:
  include:
  - name: "Ruby: 3.3 (nats-server@main)"
    rvm: "3.3.5"
    env:
    - NATS_SERVER_VERSION=main
  allow_failures:
    - name: "Ruby: 3.3 (nats-server@main)"
